// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package grpc_client

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ScalePredictorClient is the client API for ScalePredictor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ScalePredictorClient interface {
	Predict(ctx context.Context, in *PredictRequest, opts ...grpc.CallOption) (*PredictResponse, error)
}

type scalePredictorClient struct {
	cc grpc.ClientConnInterface
}

func NewScalePredictorClient(cc grpc.ClientConnInterface) ScalePredictorClient {
	return &scalePredictorClient{cc}
}

func (c *scalePredictorClient) Predict(ctx context.Context, in *PredictRequest, opts ...grpc.CallOption) (*PredictResponse, error) {
	out := new(PredictResponse)
	err := c.cc.Invoke(ctx, "/scale_predictor.ScalePredictor/Predict", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScalePredictorServer is the server API for ScalePredictor service.
// All implementations must embed UnimplementedScalePredictorServer
// for forward compatibility
type ScalePredictorServer interface {
	Predict(context.Context, *PredictRequest) (*PredictResponse, error)
	mustEmbedUnimplementedScalePredictorServer()
}

// UnimplementedScalePredictorServer must be embedded to have forward compatible implementations.
type UnimplementedScalePredictorServer struct {
}

func (UnimplementedScalePredictorServer) Predict(context.Context, *PredictRequest) (*PredictResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Predict not implemented")
}
func (UnimplementedScalePredictorServer) mustEmbedUnimplementedScalePredictorServer() {}

// UnsafeScalePredictorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ScalePredictorServer will
// result in compilation errors.
type UnsafeScalePredictorServer interface {
	mustEmbedUnimplementedScalePredictorServer()
}

func RegisterScalePredictorServer(s grpc.ServiceRegistrar, srv ScalePredictorServer) {
	s.RegisterService(&ScalePredictor_ServiceDesc, srv)
}

func _ScalePredictor_Predict_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PredictRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScalePredictorServer).Predict(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scale_predictor.ScalePredictor/Predict",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScalePredictorServer).Predict(ctx, req.(*PredictRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ScalePredictor_ServiceDesc is the grpc.ServiceDesc for ScalePredictor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ScalePredictor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "scale_predictor.ScalePredictor",
	HandlerType: (*ScalePredictorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Predict",
			Handler:    _ScalePredictor_Predict_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "scale_predictor.proto",
}
